name: Hello World Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print message
      run: echo "This is my first project"

    - name: Transition Jira Issue to To Do
      env:
        JIRA_USERNAME: "Musafir's Time"  # Replace with your actual username
        JIRA_API_TOKEN: "ATATT3xFfGF0z00NdqqUM11nJnVt_Lk2myXlguY6yyn_jMSkH_ZP0BhT1t7hxh7frnx1YZvozzf9OvhjVYCjZdMlTU-ie2Df5j2k8HyBKiHRjhbdHPdDhnkmkmX-nPxJN0Muencbb--zCKZOyVPYnT8sgjv3tOYxtT8QO07forRTk-9Bk1KFgwA=1A9C6FD2"  # Replace with your actual token
        JIRA_BASE_URL: "https://jattaashir.atlassian.net"
        ISSUE_KEY: "HELLO-123"  # Replace with your actual issue key
      run: |
        curl -D- -u $JIRA_USERNAME:$JIRA_API_TOKEN -X POST \
        --data '{"transition": {"id": "11"}}' \
        -H "Content-Type: application/json" \
        $JIRA_BASE_URL/rest/api/2/issue/$ISSUE_KEY/transitions
